version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    networks:
      - app-network

  service2:
    build: ./service_2
    container_name: service2
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy

networks:
  app-network:
    driver: bridge